# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# Copy .csproj and restore as distinct layers
COPY *.sln .
COPY APIWeb/*.csproj ./APIWeb/
COPY Core/*.csproj ./Core/
COPY EmailService/*.csproj ./EmailService/
COPY Infraestructure/*.csproj ./Infraestructure/
COPY Services/*.csproj ./Services/

RUN dotnet restore 

# copy everything else and build app
COPY APIWeb/. ./APIWeb/
COPY Core/. ./Core/
COPY EmailService/. ./EmailService/
COPY Infraestructure/. ./Infraestructure/
COPY Services/. ./Services/

WORKDIR /app/APIWeb
RUN dotnet publish -c Release -o out 

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app

COPY --from=build /app/APIWeb/out ./
ENTRYPOINT ["dotnet", "APIWeb.dll"]